export const palavrasIrrelevantes = [
  'o', 'a', 'os', 'as', 'um', 'uma', 'uns', 'umas',
  'de', 'em', 'por', 'para', 'pra', 'com', 'sobre', 'entre', 'até', 'como', 'sem',
  'desde', 'após', 'diante', 'e', 'ou', 'mas', 'porque', 'embora', 'apesar', 'logo',
  'então', 'quando', 'se', 'que', 'eu', 'tu', 'ele', 'ela', 'nós', 'vós', 'eles', 'elas', 'meu', 'minha',
  'seu', 'sua', 'deles', 'delas', 'esse', 'essa', 'aquilo', 'quem',
  'ser', 'estar', 'ter', 'fazer', 'poder', 'dever', 'querer', 'ficar', 'haver',
  'ontem', 'hoje', 'sempre', 'nunca', 'muito', 'pouco', 'demais', 'tantos', 'tantas',
  'grande', 'pequeno', 'bom', 'novo', 'velho', 'legal', 'bonito', 'mais', 'menos',
  'verdadeiro', 'falso', 'gente', 'pessoa', 'todo', 'toda', 'qualquer', 'cada',
  'algum', 'alguma', 'nenhum', 'nenhuma', 'sim', 'não', 'já', 'agora', 'aqui',
  'lá', 'onde', 'quem', 'fazer', 'ter', 'dar', 'dizer', 'falar', 'ir', 'vir',
  'ver', 'ouvir', 'pensar', 'sentir', 'quero', 'preciso', 'acho', 'sinto', 'gosto',
  'ando', 'fico', 'estou', 'sou', 'falar', 'fala', 'fake', 'sao', 'carlos',
  'veras', 'deputado', 'acho', 'pra', 'para', 'acredito', 'gostaria', 'possa',
  'poder', 'fazer', 'fiz', 'fizemos', 'fizeram', 'fizeste', 'fizestes', 'fizera',
  'mandato', 'mandatos', 'eleicoes', 'eleicao', 'eleitor', 'eleitores',
  'eleitora', 'eleitoras', 'voto', 'votos', 'votacao', 'votacoes', 'candidato',
  'candidatos', 'candidata', 'candidatas', 'partido', 'partidos', 'politico',
  'politicos', 'politica', 'politicas', 'governo', 'governos', 'governador',
  'nele','nela','neles','nelas','nos','nossa','nossas','nosso','nossos',
  'meus','minhas','teus','tuas','teu','tua','teus','tuas','seus','suas',
  'seu','sua','seus','suas','deles','delas','meu','minha','teu','tua',
  'teus', 'tuas', 'seus', 'suas', 'deles', 'delas', 'meu', 'minha', 'teu',
  'tua', 'teus', 'tuas', 'seus', 'suas', 'deles', 'delas', 'meu', 'minha',
  'trazer', 'traz', 'trazendo', 'trazendo', 'trazer', 'trazendo', 'trazendo',
  'moro', 'morando', 'morar', 'morando', 'mora', 'morando', 'morar',
  'senhor' , 'senhora', 'senhores', 'senhoras', 'vossa', 'vossos', 'vossas',
  'chegar', 'chegou', 'chegando', 'chegamos', 'chegaram', 'chegaste',
  'inclusive', 'inclusiva', 'inclusivos', 'inclusivas', 'inclusao', 'inclusões',
  'falei', 'falou', 'falando', 'falamos', 'falaram', 'falaste', 'falastes',
];
